"""The framework catalog — every named framework the requester listed (86
distinct entries across the 9 categories; "Scenario Planning" was listed
under both Strategy and Risk verbatim, so it is registered ONCE, under Risk
(its more decision-oriented home), tagged ``strategy`` so selection/search
still finds it for strategy engagements — see the self-review for this
explicit call).

**Data-driven, not hand-written classes** — the concrete mechanism behind
"do not hardcode framework execution logic; register them," the same pattern
``app.consulting.workflow.standard_workflow`` established for engagement
categories. Every framework is a ``_Spec`` tuple fed through ``_build()``;
adding framework #87 is one more ``_Spec`` entry, never a new class.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.consulting.models import EngagementCategory as EC
from app.knowledge.models import (
    ConfidenceModel,
    FrameworkCategory,
    FrameworkDefinition,
    FrameworkQualityGate,
    OutputSchema,
)

_F = FrameworkCategory


@dataclass(frozen=True)
class _Spec:
    key: str
    name: str
    category: FrameworkCategory
    purpose: str
    when_to_use: tuple[str, ...]
    when_not_to_use: tuple[str, ...]
    required_inputs: tuple[str, ...]
    optional_inputs: tuple[str, ...]
    required_evidence: tuple[str, ...]
    outputs: tuple[str, ...]
    engagements: tuple[EC, ...]
    limitations: tuple[str, ...] = ()
    assumptions: tuple[str, ...] = ()
    dependencies: tuple[str, ...] = ()
    confidence_method: str = "evidence_weighted"
    industries: tuple[str, ...] = ("all",)
    duration_days: float = 2.0
    tags: tuple[str, ...] = ()


def _build(spec: _Spec) -> FrameworkDefinition:
    gates = [
        FrameworkQualityGate(
            id=f"gate.{spec.key}.inputs",
            check_kind="required_inputs_present",
            description="All required inputs supplied",
        ),
    ]
    if spec.required_evidence:
        gates.append(
            FrameworkQualityGate(
                id=f"gate.{spec.key}.evidence",
                check_kind="required_evidence_present",
                description="All required evidence supplied",
            )
        )
    if spec.dependencies:
        gates.append(
            FrameworkQualityGate(
                id=f"gate.{spec.key}.dependencies",
                check_kind="dependency_completion",
                description="All dependency frameworks executed first",
            )
        )
    return FrameworkDefinition(
        id=spec.key,
        name=spec.name,
        category=spec.category,
        version="1.0.0",
        description=spec.purpose,
        purpose=spec.purpose,
        when_to_use=spec.when_to_use,
        when_not_to_use=spec.when_not_to_use,
        required_inputs=spec.required_inputs,
        optional_inputs=spec.optional_inputs,
        required_evidence=spec.required_evidence,
        output_schema=OutputSchema(fields=spec.outputs),
        quality_gates=tuple(gates),
        assumptions=spec.assumptions,
        limitations=spec.limitations,
        dependencies=spec.dependencies,
        confidence_model=ConfidenceModel(method=spec.confidence_method),
        supported_engagements=spec.engagements,
        supported_industries=spec.industries,
        estimated_duration_days=spec.duration_days,
        tags=spec.tags,
    )


_SPECS: tuple[_Spec, ...] = (
    # ---- Strategy (15, incl. Growth Share Analysis; Scenario Planning under Risk) --
    _Spec(
        "five_forces",
        "Porter's Five Forces",
        _F.STRATEGY,
        "Assess industry structural attractiveness via five competitive forces.",
        ("Entering a new market", "Assessing industry profitability potential"),
        ("Problem is internal/operational, not competitive dynamics",),
        ("industry definition", "competitor list"),
        ("regulatory context",),
        ("industry reports", "competitor financials"),
        ("force ratings (1-5)", "overall attractiveness score", "key threats"),
        (
            EC.MARKET_ENTRY,
            EC.BUSINESS_STRATEGY,
            EC.CORPORATE_STRATEGY,
            EC.DUE_DILIGENCE,
        ),
        limitations=("static snapshot; doesn't capture pace of change",),
        assumptions=("industry boundaries are correctly drawn",),
        tags=("classic", "industry-analysis"),
    ),
    _Spec(
        "value_chain",
        "Value Chain Analysis",
        _F.STRATEGY,
        "Decompose a firm's activities to locate "
        "sources of cost or differentiation advantage.",
        (
            "Diagnosing where margin is created or lost",
            "Comparing to competitors activity-by-activity",
        ),
        ("Firm-level activity data is unavailable",),
        ("activity cost breakdown", "org chart"),
        ("competitor activity benchmarks",),
        ("cost accounting data",),
        ("primary/support activity map", "margin by activity", "advantage sources"),
        (EC.BUSINESS_STRATEGY, EC.COST_REDUCTION, EC.OPERATIONAL_EXCELLENCE),
        limitations=("activity boundaries can be drawn inconsistently across firms",),
        tags=("classic", "cost"),
    ),
    _Spec(
        "vrio",
        "VRIO Analysis",
        _F.STRATEGY,
        "Test whether a resource/capability is a "
        "source of sustained competitive advantage.",
        ("Evaluating whether a claimed core strength is real",),
        ("No specific resource/capability has been identified to test",),
        ("candidate resource/capability list",),
        (),
        ("competitor capability comparisons",),
        ("VRIO rating per resource", "advantage classification"),
        (EC.CORPORATE_STRATEGY, EC.BUSINESS_STRATEGY, EC.DUE_DILIGENCE),
        limitations=("ratings are qualitative judgment calls",),
        tags=("classic", "resource-based-view"),
    ),
    _Spec(
        "swot",
        "SWOT Analysis",
        _F.STRATEGY,
        "Structure internal strengths/weaknesses "
        "against external opportunities/threats.",
        (
            "Early-stage framing of a strategic situation",
            "Synthesizing findings from other frameworks",
        ),
        ("Used alone as the final analysis rather than a synthesis step",),
        ("internal capability assessment", "external market scan"),
        (),
        (),
        ("strengths", "weaknesses", "opportunities", "threats", "so/wt implications"),
        tuple(EC),
        limitations=("prone to shallow, unprioritized lists without discipline",),
        dependencies=("five_forces", "pestle"),
        tags=("classic", "synthesis"),
    ),
    _Spec(
        "pestle",
        "PESTLE Analysis",
        _F.STRATEGY,
        "Scan macro-environmental factors (Political, Economic, "
        "Social, Technological, Legal, Environmental).",
        (
            "Market entry macro-context scan",
            "Regulatory/technology disruption assessment",
        ),
        ("Problem is firm-specific, not macro-environmental",),
        ("target market/geography",),
        (),
        ("regulatory filings", "macro data sources"),
        ("factor ratings by category", "top macro risks/opportunities"),
        (
            EC.MARKET_ENTRY,
            EC.CORPORATE_STRATEGY,
            EC.SCENARIO_PLANNING,
            EC.RISK_ASSESSMENT,
        ),
        limitations=("breadth over depth; can surface low-signal factors",),
        tags=("classic", "macro"),
    ),
    _Spec(
        "bcg_matrix",
        "BCG Growth-Share Matrix",
        _F.STRATEGY,
        "Classify business units/products by market "
        "growth rate vs. relative market share.",
        ("Portfolio resource-allocation decisions across multiple units",),
        ("Single-product or single-business-unit engagements",),
        ("unit revenue/growth data", "relative market share data"),
        (),
        ("market share data",),
        ("quadrant classification per unit", "portfolio balance assessment"),
        (EC.PORTFOLIO_STRATEGY, EC.CORPORATE_STRATEGY),
        limitations=(
            "market share as sole proxy for competitive strength is reductive",
        ),
        tags=("classic", "portfolio"),
    ),
    _Spec(
        "ge_mckinsey_matrix",
        "GE-McKinsey Nine-Box Matrix",
        _F.STRATEGY,
        "Classify business units by industry attractiveness "
        "vs. competitive strength (multi-factor).",
        ("Portfolio decisions needing more nuance than BCG's two-axis model",),
        ("Only one or two units are in scope (little portfolio contrast)",),
        ("industry attractiveness factors", "competitive strength factors"),
        (),
        (),
        ("nine-box placement per unit", "invest/hold/harvest recommendation"),
        (EC.PORTFOLIO_STRATEGY, EC.CORPORATE_STRATEGY, EC.INVESTMENT_EVALUATION),
        dependencies=("five_forces",),
        limitations=("factor weighting is subjective",),
        tags=("classic", "portfolio"),
    ),
    _Spec(
        "ansoff_matrix",
        "Ansoff Matrix",
        _F.STRATEGY,
        "Map growth options by product (existing/new) x market (existing/new).",
        (
            "Structuring growth strategy options",
            "Comparing risk profile of growth paths",
        ),
        ("Growth direction is already decided and only execution remains",),
        ("current product/market footprint",),
        ("growth targets",),
        (),
        ("quadrant options", "relative risk ranking"),
        (EC.GROWTH_STRATEGY, EC.CORPORATE_STRATEGY, EC.MARKET_ENTRY),
        limitations=("does not itself size the opportunity in each quadrant",),
        tags=("classic", "growth"),
    ),
    _Spec(
        "blue_ocean",
        "Blue Ocean Strategy",
        _F.STRATEGY,
        "Identify uncontested market space via the four-actions "
        "framework (eliminate/reduce/raise/create).",
        (
            "Highly commoditized markets",
            "Seeking differentiation beyond incremental improvement",
        ),
        (
            "Market is genuinely nascent with no "
            "comparable competitor set to contrast against",
        ),
        ("industry value-curve factors", "competitor offering comparison"),
        (),
        (),
        ("strategy canvas", "four-actions grid", "new value curve"),
        (EC.BUSINESS_STRATEGY, EC.INNOVATION_STRATEGY, EC.PRODUCT_STRATEGY),
        limitations=(
            "execution risk of an untested value proposition is not assessed",
        ),
        tags=("differentiation",),
    ),
    _Spec(
        "three_horizons",
        "Three Horizons Model",
        _F.STRATEGY,
        "Balance investment across core (H1), emerging "
        "(H2), and future-option (H3) businesses.",
        ("Innovation portfolio balance reviews", "Long-range planning conversations"),
        ("Single, near-term initiative with no portfolio context",),
        ("current initiative/investment list",),
        (),
        (),
        ("horizon classification", "investment balance assessment"),
        (EC.INNOVATION_STRATEGY, EC.CORPORATE_STRATEGY, EC.PORTFOLIO_STRATEGY),
        tags=("innovation", "portfolio"),
    ),
    _Spec(
        "core_competency",
        "Core Competency Analysis",
        _F.STRATEGY,
        "Identify capabilities that are valuable, hard "
        "to imitate, and applicable across markets.",
        ("Deciding what to build in-house vs. outsource", "Diversification decisions"),
        ("No credible capability inventory exists yet",),
        ("capability inventory",),
        (),
        ("competitor capability comparison",),
        ("core competency shortlist", "applicability across markets"),
        (EC.CORPORATE_STRATEGY, EC.PORTFOLIO_STRATEGY),
        dependencies=("vrio",),
        tags=("resource-based-view",),
    ),
    _Spec(
        "capability_assessment",
        "Capability Assessment",
        _F.STRATEGY,
        "Rate organizational capabilities against what the strategy requires.",
        ("Strategy-to-execution gap diagnosis",),
        ("No target strategy has been articulated to assess against",),
        ("capability inventory", "strategic priorities"),
        (),
        ("capability maturity data",),
        ("capability gap map", "priority build/buy/partner list"),
        (EC.CORPORATE_STRATEGY, EC.ORGANIZATIONAL_DESIGN, EC.DIGITAL_TRANSFORMATION),
        tags=("capability",),
    ),
    _Spec(
        "strategic_positioning",
        "Strategic Positioning Analysis",
        _F.STRATEGY,
        "Map the firm's chosen position (cost, "
        "differentiation, focus) against competitors.",
        ("Clarifying or resetting competitive positioning",),
        ("Firm has no meaningful competitive set to position against",),
        ("competitor offering comparison", "target customer segment"),
        (),
        (),
        ("positioning map", "recommended positioning statement"),
        (EC.BUSINESS_STRATEGY, EC.GO_TO_MARKET, EC.PRICING_STRATEGY),
        dependencies=("five_forces",),
        tags=("positioning",),
    ),
    _Spec(
        "growth_share_analysis",
        "Growth Share Analysis",
        _F.STRATEGY,
        "Broader growth-vs-share diagnostic combining "
        "BCG classification with trend and momentum data.",
        ("Ongoing portfolio monitoring beyond a single-point-in-time BCG snapshot",),
        ("A one-off snapshot suffices (use bcg_matrix instead)",),
        ("historical unit revenue/growth series", "market share trend data"),
        (),
        (),
        ("trended quadrant migration", "momentum-adjusted priority list"),
        (EC.PORTFOLIO_STRATEGY, EC.CORPORATE_STRATEGY),
        dependencies=("bcg_matrix",),
        tags=("portfolio", "trend"),
    ),
    # ---- Market & Growth (10) --------------------------------------------
    _Spec(
        "tam_sam_som",
        "TAM/SAM/SOM Market Sizing",
        _F.MARKET_GROWTH,
        "Size total, serviceable, and obtainable "
        "market opportunity top-down and bottom-up.",
        ("Any market-entry or new-product investment case",),
        ("Market is already precisely known from recent, reliable data",),
        ("target segment definition", "geography"),
        ("pricing assumptions",),
        ("market research data", "industry reports"),
        ("TAM", "SAM", "SOM", "sizing methodology + assumptions"),
        (
            EC.MARKET_ENTRY,
            EC.BUSINESS_CASE,
            EC.INVESTMENT_EVALUATION,
            EC.GROWTH_STRATEGY,
        ),
        limitations=(
            "top-down and bottom-up estimates often diverge without triangulation",
        ),
        confidence_method="data_completeness",
        tags=("sizing",),
    ),
    _Spec(
        "customer_segmentation",
        "Customer Segmentation",
        _F.MARKET_GROWTH,
        "Group customers by needs, behavior, or value to target strategy and offers.",
        ("Go-to-market design", "Pricing or product prioritization"),
        ("Customer base is too small/homogeneous to meaningfully segment",),
        ("customer data (behavioral or survey)",),
        ("firmographic data",),
        ("customer/transaction data",),
        ("segment definitions", "segment size", "segment value/needs profile"),
        (EC.GO_TO_MARKET, EC.PRICING_STRATEGY, EC.PRODUCT_STRATEGY, EC.GROWTH_STRATEGY),
        tags=("segmentation",),
    ),
    _Spec(
        "market_attractiveness",
        "Market Attractiveness Assessment",
        _F.MARKET_GROWTH,
        "Score candidate markets on size, growth, competitive intensity, and fit.",
        ("Prioritizing among multiple market-entry candidates",),
        ("Only one market is under consideration",),
        ("candidate market list", "scoring criteria"),
        (),
        ("market research data",),
        ("attractiveness score per market", "ranked shortlist"),
        (EC.MARKET_ENTRY, EC.GROWTH_STRATEGY, EC.PORTFOLIO_STRATEGY),
        dependencies=("tam_sam_som", "five_forces"),
        tags=("prioritization",),
    ),
    _Spec(
        "competitive_positioning",
        "Competitive Positioning Map",
        _F.MARKET_GROWTH,
        "Plot competitors on the 2 dimensions "
        "customers value most to find white space.",
        ("Identifying differentiation opportunity", "Repositioning decisions"),
        ("Fewer than 2 meaningful competitors exist",),
        ("competitor offering data", "customer value-driver ranking"),
        (),
        (),
        ("positioning map", "white-space identification"),
        (EC.GO_TO_MARKET, EC.BUSINESS_STRATEGY, EC.PRODUCT_STRATEGY),
        tags=("positioning",),
    ),
    _Spec(
        "customer_journey",
        "Customer Journey Mapping",
        _F.MARKET_GROWTH,
        "Map the end-to-end customer experience to find friction and drop-off points.",
        ("Conversion/retention diagnosis", "GTM or product experience redesign"),
        ("Customer interaction data does not exist yet (pre-launch)",),
        ("customer touchpoint data",),
        ("qualitative interview notes",),
        ("funnel/analytics data",),
        ("journey stages", "friction points", "drop-off rates"),
        (EC.GO_TO_MARKET, EC.PRODUCT_STRATEGY, EC.OPERATIONAL_EXCELLENCE),
        tags=("customer-experience",),
    ),
    _Spec(
        "gtm_assessment",
        "Go-to-Market Assessment",
        _F.MARKET_GROWTH,
        "Evaluate channel, messaging, and sales-motion fit for a launch or expansion.",
        ("New product/market launch planning",),
        ("Go-to-market is already executing at scale with clear signal",),
        ("target segment", "channel options"),
        (),
        ("channel performance data",),
        ("channel fit ranking", "GTM motion recommendation"),
        (EC.GO_TO_MARKET, EC.MARKET_ENTRY, EC.PRODUCT_STRATEGY),
        dependencies=("customer_segmentation",),
        tags=("gtm",),
    ),
    _Spec(
        "pricing_analysis",
        "Pricing Analysis",
        _F.MARKET_GROWTH,
        "Determine willingness-to-pay and optimal price point/structure.",
        ("New pricing decisions", "Pricing model changes"),
        ("No customer willingness-to-pay data can be gathered at all",),
        ("cost structure", "competitor pricing"),
        ("willingness-to-pay survey data",),
        ("pricing survey or transaction data",),
        ("recommended price point/range", "elasticity estimate"),
        (EC.PRICING_STRATEGY, EC.BUSINESS_CASE, EC.PRODUCT_STRATEGY),
        tags=("pricing",),
    ),
    _Spec(
        "market_entry_assessment",
        "Market Entry Assessment",
        _F.MARKET_GROWTH,
        "Composite go/no-go and entry-mode assessment for a new market.",
        ("Final market-entry decision synthesis",),
        ("Used as a first-pass scan (use pestle/five_forces first)",),
        ("market sizing", "competitive assessment", "regulatory scan"),
        (),
        (),
        ("go/no-go recommendation basis", "entry mode options"),
        (EC.MARKET_ENTRY,),
        dependencies=("tam_sam_som", "five_forces", "pestle"),
        tags=("synthesis", "market-entry"),
    ),
    _Spec(
        "growth_diagnostic",
        "Growth Diagnostic",
        _F.MARKET_GROWTH,
        "Decompose growth (or stalled growth) into "
        "volume, price, mix, and churn drivers.",
        ("Diagnosing a growth slowdown", "Prioritizing growth levers"),
        ("Business has no revenue history to decompose",),
        ("revenue/volume history by segment",),
        (),
        ("transaction/revenue data",),
        ("growth decomposition by driver", "prioritized lever list"),
        (EC.GROWTH_STRATEGY, EC.FINANCIAL_PERFORMANCE),
        confidence_method="data_completeness",
        tags=("growth", "diagnostic"),
    ),
    _Spec(
        "demand_forecasting",
        "Demand Forecasting",
        _F.MARKET_GROWTH,
        "Project future demand from historical "
        "trend, seasonality, and driver variables.",
        ("Capacity, inventory, or investment planning",),
        ("Fewer than 2-3 periods of historical data exist",),
        ("historical demand data",),
        ("driver/leading-indicator data",),
        ("historical sales data",),
        ("demand forecast (base/upside/downside)", "key drivers"),
        (EC.SUPPLY_CHAIN, EC.FINANCIAL_PERFORMANCE, EC.BUSINESS_CASE),
        confidence_method="data_completeness",
        tags=("forecasting",),
    ),
    # ---- Operations (10) ----------------------------------------------------
    _Spec(
        "lean",
        "Lean (Waste Elimination)",
        _F.OPERATIONS,
        "Identify and eliminate the 8 wastes across "
        "a process to improve flow and cost.",
        ("Process efficiency engagements", "Cost-to-serve reduction"),
        ("Process is not yet stable enough to observe repeatedly",),
        ("process walk-through/observation data",),
        (),
        ("process cycle-time data",),
        ("waste inventory by type", "flow improvement opportunities"),
        (EC.OPERATIONAL_EXCELLENCE, EC.PROCESS_OPTIMIZATION, EC.COST_REDUCTION),
        tags=("lean", "classic"),
    ),
    _Spec(
        "six_sigma",
        "Six Sigma (DMAIC)",
        _F.OPERATIONS,
        "Reduce process variation/defects via Define-Measure-Analyze-Improve-Control.",
        ("Quality/defect-rate problems with measurable data",),
        ("Problem is not process-variation-driven (e.g. strategic, not operational)",),
        ("process performance data", "defect/error data"),
        (),
        ("process control data",),
        ("root-cause statistical analysis", "capability index (Cpk)", "control plan"),
        (EC.OPERATIONAL_EXCELLENCE, EC.PROCESS_OPTIMIZATION),
        confidence_method="data_completeness",
        tags=("six-sigma", "classic"),
    ),
    _Spec(
        "theory_of_constraints",
        "Theory of Constraints",
        _F.OPERATIONS,
        "Find and exploit the single bottleneck limiting system throughput.",
        ("Throughput-limited operations", "Capacity investment prioritization"),
        ("System has no clear single constraint (fully balanced)",),
        ("process flow/throughput data",),
        (),
        ("throughput/cycle-time data",),
        ("constraint identification", "exploit/subordinate plan"),
        (EC.OPERATIONAL_EXCELLENCE, EC.SUPPLY_CHAIN, EC.PROCESS_OPTIMIZATION),
        dependencies=("bottleneck_analysis",),
        tags=("toc",),
    ),
    _Spec(
        "value_stream_mapping",
        "Value Stream Mapping",
        _F.OPERATIONS,
        "Visualize material and information flow "
        "end-to-end to find non-value-add steps.",
        ("End-to-end process redesign", "Lead-time reduction"),
        ("Process spans a single, already well-understood step",),
        ("process step data with timing",),
        (),
        ("process cycle-time data",),
        ("current-state map", "future-state map", "lead-time reduction opportunities"),
        (EC.PROCESS_OPTIMIZATION, EC.OPERATIONAL_EXCELLENCE, EC.SUPPLY_CHAIN),
        dependencies=("process_mapping",),
        tags=("lean", "mapping"),
    ),
    _Spec(
        "process_mapping",
        "Process Mapping",
        _F.OPERATIONS,
        "Document a process's actual steps, owners, and handoffs as a baseline.",
        ("Any operations engagement's first diagnostic step",),
        ("A validated map already exists and is current",),
        ("process walk-through/interviews",),
        (),
        (),
        ("swimlane process map", "handoff/owner list"),
        (EC.PROCESS_OPTIMIZATION, EC.OPERATIONAL_EXCELLENCE, EC.CHANGE_MANAGEMENT),
        duration_days=1.5,
        tags=("mapping", "baseline"),
    ),
    _Spec(
        "capacity_analysis",
        "Capacity Analysis",
        _F.OPERATIONS,
        "Compare available capacity to demand to identify slack or shortfall.",
        ("Capacity investment or utilization decisions",),
        ("Demand data is unavailable or too volatile to baseline",),
        ("capacity data", "demand data"),
        (),
        ("utilization data",),
        ("capacity utilization rate", "shortfall/slack by period"),
        (EC.SUPPLY_CHAIN, EC.OPERATIONAL_EXCELLENCE, EC.BUSINESS_CASE),
        dependencies=("demand_forecasting",),
        confidence_method="data_completeness",
        tags=("capacity",),
    ),
    _Spec(
        "bottleneck_analysis",
        "Bottleneck Analysis",
        _F.OPERATIONS,
        "Locate the process step with the lowest "
        "throughput constraining the whole system.",
        ("Throughput problems with step-level data available",),
        ("Step-level throughput data cannot be measured",),
        ("step-level throughput/cycle-time data",),
        (),
        ("throughput data",),
        ("bottleneck step", "throughput impact estimate"),
        (EC.OPERATIONAL_EXCELLENCE, EC.PROCESS_OPTIMIZATION, EC.SUPPLY_CHAIN),
        dependencies=("process_mapping",),
        tags=("diagnostic",),
    ),
    _Spec(
        "operational_maturity",
        "Operational Maturity Assessment",
        _F.OPERATIONS,
        "Rate operations against a maturity model (ad hoc -> optimized).",
        ("Baselining before a transformation program",),
        ("No transformation or improvement program is planned",),
        ("maturity model criteria", "current-state operations data"),
        (),
        (),
        ("maturity level per dimension", "gap-to-target-level list"),
        (EC.OPERATIONAL_EXCELLENCE, EC.DIGITAL_TRANSFORMATION),
        tags=("maturity",),
    ),
    _Spec(
        "supply_chain_assessment",
        "Supply Chain Assessment",
        _F.OPERATIONS,
        "Evaluate supply chain resilience, cost, and service level end-to-end.",
        ("Supply chain redesign or resilience engagements",),
        ("Supply chain is single-node/trivial (no multi-tier structure)",),
        ("supplier/network data", "service level data"),
        (),
        ("supplier performance data",),
        ("network map", "cost-to-serve by node", "resilience risk rating"),
        (EC.SUPPLY_CHAIN,),
        tags=("supply-chain",),
    ),
    _Spec(
        "ops_operating_model_assessment",
        "Operating Model Assessment (Operations)",
        _F.OPERATIONS,
        "Assess how work actually gets delivered "
        "(process, tools, governance) vs. how it should.",
        ("Operations transformation scoping",),
        ("Scope is a single process, not the end-to-end delivery model",),
        ("current delivery model documentation",),
        (),
        (),
        ("current vs. target operating model gap", "delivery-model recommendation"),
        (EC.OPERATIONAL_EXCELLENCE, EC.DIGITAL_TRANSFORMATION, EC.COST_REDUCTION),
        tags=("operating-model",),
    ),
    # ---- Finance (11) -------------------------------------------------------
    _Spec(
        "dcf",
        "Discounted Cash Flow (DCF)",
        _F.FINANCE,
        "Value an asset/business as the present value of projected future cash flows.",
        ("Valuation for investment, M&A, or business case decisions",),
        ("Cash flows cannot be credibly projected (too early-stage/volatile)",),
        ("cash flow projections", "discount rate"),
        ("terminal growth rate",),
        ("financial statements",),
        ("present value", "NPV", "valuation range"),
        (EC.INVESTMENT_EVALUATION, EC.DUE_DILIGENCE, EC.BUSINESS_CASE, EC.MARKET_ENTRY),
        confidence_method="data_completeness",
        tags=("valuation", "quant"),
    ),
    _Spec(
        "npv",
        "Net Present Value (NPV)",
        _F.FINANCE,
        "Compare the present value of an investment's inflows to its cost.",
        ("Go/no-go investment decisions with cash flow estimates",),
        ("Discount rate cannot be reasonably estimated",),
        ("cash flow projections", "discount rate", "initial investment"),
        (),
        ("financial projections",),
        ("NPV", "decision recommendation (invest/reject)"),
        (EC.INVESTMENT_EVALUATION, EC.BUSINESS_CASE),
        confidence_method="data_completeness",
        tags=("valuation", "quant"),
    ),
    _Spec(
        "irr",
        "Internal Rate of Return (IRR)",
        _F.FINANCE,
        "Solve for the discount rate at which an investment's NPV equals zero.",
        ("Comparing investment options on a rate-of-return basis",),
        ("Cash flow sign pattern produces multiple/no real IRR solutions",),
        ("cash flow projections",),
        (),
        ("financial projections",),
        ("IRR", "comparison to hurdle rate"),
        (EC.INVESTMENT_EVALUATION, EC.BUSINESS_CASE),
        dependencies=("npv",),
        confidence_method="data_completeness",
        tags=("valuation", "quant"),
    ),
    _Spec(
        "payback_period",
        "Payback Period Analysis",
        _F.FINANCE,
        "Compute how long an investment takes to recover its initial cost.",
        ("Quick-screen investment comparisons", "Liquidity-sensitive decisions"),
        ("Used as the sole criterion for a large strategic investment",),
        ("cash flow projections", "initial investment"),
        (),
        (),
        ("payback period (years)",),
        (EC.INVESTMENT_EVALUATION, EC.BUSINESS_CASE),
        limitations=("ignores time value of money and cash flows after payback",),
        tags=("valuation", "quant"),
    ),
    _Spec(
        "sensitivity_analysis",
        "Sensitivity Analysis",
        _F.FINANCE,
        "Test how much the output changes as key assumptions vary one at a time.",
        ("Stress-testing a financial model's key assumptions",),
        ("Model has no identified key drivers to vary",),
        ("base-case model", "variable ranges"),
        (),
        (),
        ("tornado chart data", "output range per variable"),
        (EC.INVESTMENT_EVALUATION, EC.BUSINESS_CASE, EC.RISK_ASSESSMENT),
        dependencies=("dcf",),
        confidence_method="data_completeness",
        tags=("quant", "risk", "reuses-app.pipeline.sensitivity_analysis"),
    ),
    _Spec(
        "scenario_analysis",
        "Scenario Analysis (Finance)",
        _F.FINANCE,
        "Model discrete best/base/worst case "
        "scenarios rather than single-point estimates.",
        ("Presenting a range of outcomes to decision-makers",),
        ("Only one plausible future scenario exists",),
        ("base-case model", "scenario assumption sets"),
        (),
        (),
        ("scenario outputs (best/base/worst)", "probability-weighted expected value"),
        (EC.INVESTMENT_EVALUATION, EC.RISK_ASSESSMENT, EC.SCENARIO_PLANNING),
        dependencies=("dcf",),
        confidence_method="data_completeness",
        tags=("quant", "risk", "reuses-app.pipeline.scenario_evaluator"),
    ),
    _Spec(
        "unit_economics",
        "Unit Economics",
        _F.FINANCE,
        "Analyze revenue and cost per unit (customer/order/transaction) "
        "to test business model viability.",
        ("Business model viability assessment", "LTV/CAC evaluation"),
        ("Unit-level cost/revenue data cannot be isolated",),
        ("unit-level cost data", "unit-level revenue data"),
        (),
        ("cost accounting data",),
        ("contribution margin per unit", "LTV:CAC ratio"),
        (EC.BUSINESS_CASE, EC.VENTURE_VALIDATION, EC.PRODUCT_STRATEGY),
        tags=("quant", "viability"),
    ),
    _Spec(
        "breakeven_analysis",
        "Break-even Analysis",
        _F.FINANCE,
        "Solve for the volume/price at which revenue equals total cost.",
        ("Pricing or volume-target decisions",),
        ("Fixed/variable cost split cannot be determined",),
        ("fixed costs", "variable cost per unit", "price per unit"),
        (),
        (),
        ("break-even volume", "break-even revenue"),
        (EC.BUSINESS_CASE, EC.PRICING_STRATEGY),
        tags=("quant",),
    ),
    _Spec(
        "cost_structure_analysis",
        "Cost Structure Analysis",
        _F.FINANCE,
        "Decompose costs by category, driver, and fixed/variable nature.",
        ("Cost reduction engagements' diagnostic phase",),
        ("Detailed cost accounting data does not exist",),
        ("cost accounting data",),
        (),
        ("GL/cost accounting export",),
        ("cost breakdown by category/driver", "fixed vs. variable split"),
        (EC.COST_REDUCTION, EC.FINANCIAL_PERFORMANCE),
        confidence_method="data_completeness",
        tags=("cost",),
    ),
    _Spec(
        "profitability_analysis",
        "Profitability Analysis",
        _F.FINANCE,
        "Decompose profitability (DuPont-style) into "
        "margin, turnover, and leverage drivers.",
        ("Diagnosing declining or underperforming profitability",),
        ("Financial statements are unavailable or unreliable",),
        ("financial statements",),
        (),
        ("financial statements",),
        ("profitability driver decomposition", "benchmark comparison"),
        (EC.FINANCIAL_PERFORMANCE, EC.DUE_DILIGENCE, EC.COST_REDUCTION),
        confidence_method="data_completeness",
        tags=("quant", "dupont"),
    ),
    _Spec(
        "financial_benchmarking",
        "Financial Benchmarking",
        _F.FINANCE,
        "Compare a firm's financial ratios against industry peers.",
        ("Establishing whether performance is a real problem or in line with peers",),
        ("No comparable peer set exists",),
        ("financial statements", "peer set"),
        (),
        ("peer financial data",),
        ("ratio comparison table", "percentile ranking vs. peers"),
        (EC.FINANCIAL_PERFORMANCE, EC.DUE_DILIGENCE),
        tags=("benchmarking",),
    ),
    # ---- Product (10) --------------------------------------------------------
    _Spec(
        "jobs_to_be_done",
        "Jobs To Be Done",
        _F.PRODUCT,
        "Identify the functional/emotional 'job' a customer hires a product to do.",
        ("Product discovery and positioning",),
        ("Deep customer interview access is unavailable",),
        ("customer interview data",),
        (),
        ("customer interview transcripts",),
        ("job statements", "job map"),
        (EC.PRODUCT_STRATEGY, EC.INNOVATION_STRATEGY, EC.VENTURE_VALIDATION),
        tags=("jtbd", "discovery"),
    ),
    _Spec(
        "product_discovery",
        "Product Discovery",
        _F.PRODUCT,
        "Test problem/solution assumptions with customers before committing to build.",
        ("Pre-build validation of a new product/feature idea",),
        ("Product is already built and in market (use retention_analysis instead)",),
        ("target user segment", "problem hypothesis"),
        (),
        ("user research data",),
        ("validated/invalidated assumptions", "prioritized problem list"),
        (EC.PRODUCT_STRATEGY, EC.VENTURE_VALIDATION, EC.INNOVATION_STRATEGY),
        dependencies=("jobs_to_be_done",),
        tags=("discovery",),
    ),
    _Spec(
        "north_star_metrics",
        "North Star Metric Framework",
        _F.PRODUCT,
        "Define the single metric that best captures durable customer value delivered.",
        ("Aligning a product org around one leading value metric",),
        ("Product has no usage data yet to validate a candidate metric",),
        ("product usage data", "value hypothesis"),
        (),
        ("product analytics data",),
        ("candidate north star metric", "supporting input metrics"),
        (EC.PRODUCT_STRATEGY,),
        tags=("metrics",),
    ),
    _Spec(
        "product_lifecycle",
        "Product Lifecycle Analysis",
        _F.PRODUCT,
        "Place a product on the introduction/growth/maturity/decline "
        "curve to guide strategy.",
        ("Deciding whether to invest, harvest, or sunset a product",),
        ("Product has less than one full sales cycle of data",),
        ("product revenue/adoption history",),
        (),
        ("product usage/revenue data",),
        ("lifecycle stage", "stage-appropriate strategy recommendation"),
        (EC.PRODUCT_STRATEGY, EC.PORTFOLIO_STRATEGY),
        tags=("lifecycle",),
    ),
    _Spec(
        "feature_prioritization",
        "Feature Prioritization (RICE/Value-Effort)",
        _F.PRODUCT,
        "Rank candidate features by reach/impact/confidence/effort or value-vs-effort.",
        ("Roadmap planning with more candidate features than capacity",),
        ("Only one feature is under consideration",),
        ("candidate feature list", "scoring inputs"),
        (),
        (),
        ("prioritized feature ranking", "scores per feature"),
        (EC.PRODUCT_STRATEGY,),
        tags=("prioritization",),
    ),
    _Spec(
        "customer_value_proposition",
        "Customer Value Proposition Design",
        _F.PRODUCT,
        "Fit product features/benefits explicitly to customer pains and gains.",
        ("Positioning or messaging design", "Product-market fit diagnosis"),
        ("Target customer segment is not yet defined",),
        ("customer pains/gains data", "product feature list"),
        (),
        (),
        ("value map", "fit assessment"),
        (EC.PRODUCT_STRATEGY, EC.GO_TO_MARKET),
        dependencies=("customer_segmentation",),
        tags=("value-proposition",),
    ),
    _Spec(
        "product_portfolio_analysis",
        "Product Portfolio Analysis",
        _F.PRODUCT,
        "Assess a multi-product portfolio for overlap, gaps, and resource allocation.",
        ("Multi-product roadmap and investment decisions",),
        ("Single-product engagement",),
        ("product portfolio revenue/growth data",),
        (),
        (),
        ("portfolio map", "overlap/gap findings"),
        (EC.PORTFOLIO_STRATEGY, EC.PRODUCT_STRATEGY),
        dependencies=("bcg_matrix",),
        tags=("portfolio",),
    ),
    _Spec(
        "product_market_fit",
        "Product-Market Fit Assessment",
        _F.PRODUCT,
        "Test whether product usage/retention/sentiment signal genuine market pull.",
        ("Deciding whether to scale GTM investment",),
        ("Product has not yet launched to real users",),
        ("retention/usage data", "customer sentiment data"),
        (),
        ("product analytics data",),
        ("PMF signal strength", "leading risk indicators"),
        (EC.PRODUCT_STRATEGY, EC.VENTURE_VALIDATION),
        dependencies=("retention_analysis",),
        confidence_method="data_completeness",
        tags=("pmf",),
    ),
    _Spec(
        "adoption_funnel",
        "Adoption Funnel Analysis",
        _F.PRODUCT,
        "Break down the acquisition-to-activation-to-adoption funnel to find drop-off.",
        ("Activation/onboarding conversion problems",),
        ("Funnel event data is not instrumented",),
        ("funnel event data",),
        (),
        ("product analytics data",),
        ("funnel conversion rates by step", "drop-off diagnosis"),
        (EC.PRODUCT_STRATEGY, EC.GO_TO_MARKET),
        confidence_method="data_completeness",
        tags=("funnel",),
    ),
    _Spec(
        "retention_analysis",
        "Retention/Cohort Analysis",
        _F.PRODUCT,
        "Track cohort retention curves to assess durable engagement and churn drivers.",
        ("Churn diagnosis", "PMF assessment input"),
        ("Fewer than 2-3 cohorts of history exist",),
        ("cohort usage data",),
        (),
        ("product usage data",),
        ("retention curves by cohort", "churn driver hypotheses"),
        (EC.PRODUCT_STRATEGY, EC.VENTURE_VALIDATION),
        confidence_method="data_completeness",
        tags=("retention",),
    ),
    # ---- Innovation (7) -------------------------------------------------------
    _Spec(
        "design_thinking",
        "Design Thinking",
        _F.INNOVATION,
        "Human-centered ideation process: empathize, define, ideate, prototype, test.",
        ("Open-ended innovation problems with unclear solution space",),
        ("Problem and solution are already well-defined (use direct execution)",),
        ("user research access",),
        (),
        ("user research data",),
        ("problem statements", "prototyped concepts", "test learnings"),
        (EC.INNOVATION_STRATEGY, EC.PRODUCT_STRATEGY, EC.VENTURE_VALIDATION),
        tags=("innovation", "human-centered"),
    ),
    _Spec(
        "lean_startup",
        "Lean Startup (Build-Measure-Learn)",
        _F.INNOVATION,
        "Validate business model assumptions via minimum viable experiments.",
        ("New venture or new-business-line validation",),
        ("Business model is already proven at scale",),
        ("riskiest assumptions list",),
        (),
        ("experiment result data",),
        ("validated learning log", "pivot/persevere recommendation"),
        (EC.VENTURE_VALIDATION, EC.INNOVATION_STRATEGY),
        dependencies=("hypothesis_validation",),
        tags=("innovation", "lean"),
    ),
    _Spec(
        "business_model_canvas",
        "Business Model Canvas",
        _F.INNOVATION,
        "Map the 9 building blocks of a business model on one page.",
        ("Structuring a new or existing business model for review",),
        ("Model is highly complex and multi-entity (canvas oversimplifies)",),
        ("business model inputs (segments, value prop, channels, etc.)",),
        (),
        (),
        ("completed canvas", "internal consistency flags"),
        (EC.VENTURE_VALIDATION, EC.BUSINESS_STRATEGY, EC.INNOVATION_STRATEGY),
        tags=("canvas",),
    ),
    _Spec(
        "value_proposition_canvas",
        "Value Proposition Canvas",
        _F.INNOVATION,
        "Map customer jobs/pains/gains against product pain-relievers/gain-creators.",
        ("Refining product-market fit at the offer level",),
        ("Customer segment is not yet defined",),
        ("customer jobs/pains/gains data", "product features"),
        (),
        (),
        ("fit map", "unaddressed pains/gains"),
        (EC.PRODUCT_STRATEGY, EC.VENTURE_VALIDATION),
        dependencies=("jobs_to_be_done",),
        tags=("canvas", "value-proposition"),
    ),
    _Spec(
        "innovation_portfolio",
        "Innovation Portfolio Management",
        _F.INNOVATION,
        "Balance innovation bets across risk/return and horizon.",
        ("Multi-initiative innovation investment reviews",),
        ("Single initiative under review",),
        ("initiative list with risk/return estimates",),
        (),
        (),
        ("portfolio balance map", "rebalancing recommendation"),
        (EC.INNOVATION_STRATEGY, EC.PORTFOLIO_STRATEGY),
        dependencies=("three_horizons",),
        tags=("portfolio", "innovation"),
    ),
    _Spec(
        "experiment_design",
        "Experiment Design",
        _F.INNOVATION,
        "Design a valid test (A/B, pilot) with clear "
        "hypothesis, metric, and success threshold.",
        ("Any claim needing empirical validation before scaling",),
        ("Sample size cannot reach statistical/practical significance",),
        ("hypothesis statement", "target metric"),
        (),
        (),
        ("experiment design spec", "success/failure threshold"),
        (EC.VENTURE_VALIDATION, EC.PRODUCT_STRATEGY, EC.INNOVATION_STRATEGY),
        tags=("experimentation",),
    ),
    _Spec(
        "hypothesis_validation",
        "Hypothesis Validation",
        _F.INNOVATION,
        "Systematically test and rate confidence "
        "in a business hypothesis using evidence.",
        ("Any engagement built around hypothesis-driven analysis",),
        ("No falsifiable hypothesis has been articulated",),
        ("hypothesis statement",),
        (),
        ("supporting/contradicting evidence",),
        ("confidence rating", "validation status"),
        tuple(EC),
        dependencies=("experiment_design",),
        tags=("hypothesis-driven",),
    ),
    # ---- Organization (8) ------------------------------------------------
    _Spec(
        "mckinsey_7s",
        "McKinsey 7S Framework",
        _F.ORGANIZATION,
        "Assess alignment across Strategy, Structure, "
        "Systems, Shared Values, Skills, Style, Staff.",
        ("Organizational effectiveness diagnosis", "Change readiness assessment"),
        ("Scope is a single narrow process, not the whole organization",),
        ("org data across all 7 dimensions",),
        (),
        (),
        ("7S alignment ratings", "misalignment findings"),
        (EC.ORGANIZATIONAL_DESIGN, EC.CHANGE_MANAGEMENT, EC.CORPORATE_STRATEGY),
        tags=("classic", "org-diagnostic"),
    ),
    _Spec(
        "raci",
        "RACI Matrix",
        _F.ORGANIZATION,
        "Clarify who is Responsible, Accountable, "
        "Consulted, and Informed per decision/task.",
        ("Decision-rights or handoff confusion", "Post-reorg role clarification"),
        ("Roles/tasks are not yet defined enough to assign",),
        ("task/decision list", "role list"),
        (),
        (),
        ("RACI matrix", "gap/overlap findings"),
        (EC.ORGANIZATIONAL_DESIGN, EC.CHANGE_MANAGEMENT),
        duration_days=1.0,
        tags=("governance",),
    ),
    _Spec(
        "stakeholder_analysis",
        "Stakeholder Analysis",
        _F.ORGANIZATION,
        "Map stakeholders by influence and interest to plan engagement approach.",
        ("Any engagement's early scoping phase", "Change management planning"),
        ("Stakeholder set is trivially small (1-2 people)",),
        ("stakeholder list",),
        (),
        (),
        ("influence/interest map", "engagement plan per stakeholder"),
        tuple(EC),
        duration_days=1.0,
        tags=("stakeholder",),
    ),
    _Spec(
        "org_operating_model",
        "Operating Model Design (Organization)",
        _F.ORGANIZATION,
        "Design how the organization is structured to deliver "
        "strategy: structure, governance, decision rights.",
        ("Post-merger integration", "Major restructuring"),
        ("Change is limited to one team (use organizational_design at smaller scope)",),
        ("current org structure", "strategic priorities"),
        (),
        (),
        ("target operating model", "transition plan"),
        (EC.ORGANIZATIONAL_DESIGN, EC.DUE_DILIGENCE, EC.CORPORATE_STRATEGY),
        dependencies=("mckinsey_7s",),
        tags=("operating-model",),
    ),
    _Spec(
        "decision_rights",
        "Decision Rights Mapping",
        _F.ORGANIZATION,
        "Clarify which role/level owns which category of decision (RAPID-style).",
        ("Slow-decision-making diagnosis",),
        ("Decisions are already fast and well-owned",),
        ("decision inventory",),
        (),
        (),
        ("decision-rights map", "bottleneck decisions"),
        (EC.ORGANIZATIONAL_DESIGN, EC.CHANGE_MANAGEMENT),
        dependencies=("raci",),
        tags=("governance",),
    ),
    _Spec(
        "organizational_design",
        "Organizational Design",
        _F.ORGANIZATION,
        "Design reporting structure, spans, and layers to fit strategy and scale.",
        ("Restructuring or scaling engagements",),
        ("No structural change is contemplated",),
        ("current org chart", "strategic priorities"),
        (),
        (),
        ("proposed org structure", "span/layer analysis"),
        (EC.ORGANIZATIONAL_DESIGN, EC.WORKFORCE_STRATEGY),
        dependencies=("mckinsey_7s",),
        tags=("org-design",),
    ),
    _Spec(
        "capability_mapping",
        "Capability Mapping (Organization)",
        _F.ORGANIZATION,
        "Inventory organizational capabilities "
        "and rate maturity against strategic need.",
        ("Workforce/skills planning", "Digital transformation readiness"),
        ("No target capability model exists to map against",),
        ("capability inventory", "role/skills data"),
        (),
        (),
        ("capability heat map", "priority build/hire/partner list"),
        (EC.WORKFORCE_STRATEGY, EC.DIGITAL_TRANSFORMATION, EC.ORGANIZATIONAL_DESIGN),
        tags=("capability",),
    ),
    _Spec(
        "governance_assessment",
        "Governance Assessment",
        _F.ORGANIZATION,
        "Evaluate decision-making bodies, escalation "
        "paths, and oversight effectiveness.",
        ("Post-incident governance reviews", "Scaling governance for growth"),
        ("Organization has no formal governance structure yet to assess",),
        ("governance body/charter data",),
        (),
        (),
        ("governance maturity rating", "gap findings"),
        (EC.ORGANIZATIONAL_DESIGN, EC.BUSINESS_CONTINUITY, EC.RISK_ASSESSMENT),
        tags=("governance",),
    ),
    # ---- Digital & AI (9) ------------------------------------------------
    _Spec(
        "digital_maturity",
        "Digital Maturity Assessment",
        _F.DIGITAL_AI,
        "Rate digital capability across customer "
        "experience, operations, and technology.",
        ("Digital transformation program scoping",),
        ("No digital transformation is contemplated",),
        ("maturity model criteria", "current-state digital capability data"),
        (),
        (),
        ("maturity score by dimension", "gap-to-target list"),
        (EC.DIGITAL_TRANSFORMATION,),
        tags=("maturity", "digital"),
    ),
    _Spec(
        "ai_readiness",
        "AI Readiness Assessment",
        _F.DIGITAL_AI,
        "Assess data, talent, infrastructure, and "
        "governance readiness for AI adoption.",
        ("Scoping an AI transformation program",),
        ("No AI use cases have been identified yet",),
        ("data infrastructure inventory", "talent/skills inventory"),
        (),
        (),
        ("readiness score by dimension", "priority gaps to close"),
        (EC.AI_TRANSFORMATION,),
        tags=("ai", "readiness"),
    ),
    _Spec(
        "automation_assessment",
        "Automation Assessment",
        _F.DIGITAL_AI,
        "Score candidate processes for automation feasibility and ROI.",
        ("Prioritizing automation investment across processes",),
        ("Candidate process list does not exist yet",),
        ("candidate process list", "process volume/cost data"),
        (),
        ("process cost data",),
        ("automation feasibility score", "ROI-ranked shortlist"),
        (EC.AUTOMATION_STRATEGY, EC.COST_REDUCTION, EC.DIGITAL_TRANSFORMATION),
        dependencies=("process_mapping",),
        confidence_method="data_completeness",
        tags=("automation",),
    ),
    _Spec(
        "technology_capability_assessment",
        "Technology Capability Assessment",
        _F.DIGITAL_AI,
        "Inventory and rate current technology capabilities against strategic needs.",
        ("Technology modernization scoping",),
        ("Technology inventory does not exist and cannot be gathered",),
        ("technology inventory",),
        (),
        (),
        ("capability rating by system", "modernization priority list"),
        (EC.TECHNOLOGY_MODERNIZATION, EC.DIGITAL_TRANSFORMATION),
        tags=("technology",),
    ),
    _Spec(
        "platform_strategy",
        "Platform Strategy Assessment",
        _F.DIGITAL_AI,
        "Evaluate whether/how to build a platform "
        "(multi-sided or internal) business model.",
        ("Assessing platform-model viability",),
        ("No multi-sided or ecosystem dynamic exists",),
        ("stakeholder/participant map", "network effect hypothesis"),
        (),
        (),
        ("platform viability assessment", "monetization model options"),
        (EC.DIGITAL_TRANSFORMATION, EC.BUSINESS_STRATEGY, EC.INNOVATION_STRATEGY),
        tags=("platform",),
    ),
    _Spec(
        "cloud_readiness",
        "Cloud Readiness Assessment",
        _F.DIGITAL_AI,
        "Assess workload suitability, cost, and risk for cloud migration.",
        ("Cloud migration program scoping",),
        ("Workload/application inventory does not exist",),
        ("application/workload inventory",),
        (),
        ("infrastructure cost data",),
        ("migration readiness rating per workload", "cost/benefit estimate"),
        (EC.TECHNOLOGY_MODERNIZATION, EC.DIGITAL_TRANSFORMATION),
        tags=("cloud",),
    ),
    _Spec(
        "data_strategy",
        "Data Strategy Assessment",
        _F.DIGITAL_AI,
        "Evaluate data quality, governance, and accessibility against business needs.",
        ("Precondition for AI/analytics investment",),
        ("No data-dependent initiative is planned",),
        ("data inventory", "data governance documentation"),
        (),
        (),
        ("data maturity rating", "priority data quality/governance gaps"),
        (EC.AI_TRANSFORMATION, EC.DIGITAL_TRANSFORMATION),
        tags=("data",),
    ),
    _Spec(
        "technology_landscape",
        "Technology Landscape Analysis",
        _F.DIGITAL_AI,
        "Map the current application/system landscape and integration points.",
        ("Baseline for any technology modernization engagement",),
        ("A current landscape map already exists and is accurate",),
        ("system/application inventory",),
        (),
        (),
        ("landscape map", "integration complexity findings"),
        (EC.TECHNOLOGY_MODERNIZATION, EC.DIGITAL_TRANSFORMATION),
        duration_days=3.0,
        tags=("landscape", "baseline"),
    ),
    _Spec(
        "architecture_assessment",
        "Architecture Assessment",
        _F.DIGITAL_AI,
        "Evaluate technical architecture against "
        "scalability, resilience, and cost criteria.",
        ("Pre-investment technical due diligence", "Modernization planning"),
        ("No architecture documentation exists to assess",),
        ("architecture documentation",),
        (),
        (),
        ("architecture rating by criterion", "risk/debt findings"),
        (EC.TECHNOLOGY_MODERNIZATION, EC.DUE_DILIGENCE),
        dependencies=("technology_landscape",),
        tags=("architecture",),
    ),
    # ---- Risk (7, incl. shared Scenario Planning) -------------------------
    _Spec(
        "risk_matrix",
        "Risk Matrix (Likelihood x Impact)",
        _F.RISK,
        "Score and rank risks by likelihood and impact to prioritize mitigation.",
        ("Any engagement needing a structured risk register",),
        ("Risks have not yet been identified/enumerated",),
        ("identified risk list",),
        (),
        (),
        ("likelihood/impact score per risk", "priority ranking"),
        (EC.RISK_ASSESSMENT, EC.DUE_DILIGENCE, EC.BUSINESS_CONTINUITY, EC.MARKET_ENTRY),
        duration_days=1.0,
        tags=("risk", "classic"),
    ),
    _Spec(
        "failure_mode_analysis",
        "Failure Mode and Effects Analysis (FMEA)",
        _F.RISK,
        "Systematically identify failure modes, causes, "
        "and effects, ranked by risk priority number.",
        ("Process/product reliability risk assessment",),
        ("Process is not well-enough understood to enumerate failure modes",),
        ("process/product step list",),
        (),
        ("historical failure data",),
        ("failure mode list", "risk priority number (RPN) per mode"),
        (EC.RISK_ASSESSMENT, EC.OPERATIONAL_EXCELLENCE, EC.BUSINESS_CONTINUITY),
        dependencies=("process_mapping",),
        tags=("risk", "fmea"),
    ),
    _Spec(
        "scenario_planning",
        "Scenario Planning",
        _F.RISK,
        "Construct plausible, divergent future "
        "scenarios to stress-test strategy robustness.",
        (
            "High-uncertainty strategic decisions",
            "Long-range planning under volatility",
        ),
        ("Near-term, low-uncertainty operational decisions",),
        ("key uncertainty drivers",),
        (),
        ("macro/industry trend data",),
        ("scenario narratives", "strategy robustness rating per scenario"),
        (EC.SCENARIO_PLANNING, EC.RISK_ASSESSMENT, EC.CORPORATE_STRATEGY),
        dependencies=("pestle",),
        tags=("strategy", "risk", "uncertainty"),
    ),
    _Spec(
        "business_continuity",
        "Business Continuity Assessment",
        _F.RISK,
        "Evaluate resilience of critical processes "
        "and recovery plans against disruption.",
        ("Continuity/resilience planning engagements",),
        ("Critical processes have not been identified",),
        ("critical process inventory", "recovery time objectives"),
        (),
        (),
        ("business impact analysis", "recovery gap findings"),
        (EC.BUSINESS_CONTINUITY, EC.RISK_ASSESSMENT),
        dependencies=("risk_matrix",),
        tags=("continuity",),
    ),
    _Spec(
        "dependency_mapping",
        "Dependency Mapping (Risk)",
        _F.RISK,
        "Map critical dependencies (systems, suppliers, "
        "people) to find single points of failure.",
        ("Resilience or concentration-risk assessment",),
        ("System/process being assessed has no external dependencies",),
        ("system/process/supplier inventory",),
        (),
        (),
        ("dependency graph", "single-point-of-failure list"),
        (EC.RISK_ASSESSMENT, EC.BUSINESS_CONTINUITY, EC.SUPPLY_CHAIN),
        tags=("dependency",),
    ),
    _Spec(
        "risk_heatmap",
        "Risk Heatmap",
        _F.RISK,
        "Visualize a risk portfolio's likelihood/impact distribution at a glance.",
        ("Executive risk reporting/synthesis",),
        ("Fewer than ~5 risks exist (a table suffices)",),
        ("scored risk list",),
        (),
        (),
        ("heatmap grid data",),
        (EC.RISK_ASSESSMENT, EC.DUE_DILIGENCE),
        dependencies=("risk_matrix",),
        duration_days=0.5,
        tags=("risk", "visualization"),
    ),
    _Spec(
        "mitigation_planning",
        "Mitigation Planning",
        _F.RISK,
        "Define specific mitigation actions, owners, "
        "and timelines for prioritized risks.",
        ("Converting a risk register into an action plan",),
        ("Risks have not yet been prioritized",),
        ("prioritized risk list",),
        (),
        (),
        ("mitigation action plan", "owner/timeline per action"),
        (EC.RISK_ASSESSMENT, EC.BUSINESS_CONTINUITY),
        dependencies=("risk_matrix",),
        tags=("risk", "action-planning"),
    ),
)


def all_framework_definitions() -> tuple[FrameworkDefinition, ...]:
    return tuple(_build(spec) for spec in _SPECS)
