"""Generate the ADR-002 traceability matrix (markdown + JSON) from the rule registry.

Run via ``make traceability``. One row per validation rule — **Rule → Validator →
Test(s)** — sourced from `state.validation.ALL_RULES` plus a scan of the validation
tests for slug-named test functions (`test_<rule_id>_...`). Guarded by
`tests/state/validation/test_traceability.py`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from state.validation import ALL_RULES

_ROOT = Path(__file__).resolve().parent.parent
_TESTS = _ROOT / "tests" / "state" / "validation"
_MD = _ROOT / "docs" / "implementation" / "traceability-ADR-002.md"
_JSON = _ROOT / "docs" / "implementation" / "traceability.json"


def _slug(rule_id: str) -> str:
    return rule_id.lower().replace("-", "_")


def _tests_for(rule_id: str) -> list[str]:
    pattern = re.compile(rf"def (test_{_slug(rule_id)}\w*)\(")
    found: list[str] = []
    for path in sorted(_TESTS.glob("*.py")):
        found.extend(pattern.findall(path.read_text(encoding="utf-8")))
    return found


def rows() -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for rule in ALL_RULES:
        module = rule.validator.__module__.rsplit(".", 1)[-1]
        result.append(
            {
                "rule_id": rule.rule_id,
                "group": rule.group.value,
                "severity": rule.severity.value,
                "adr_reference": rule.adr_reference,
                "description": rule.description,
                "validator": f"{module}.{rule.validator.__name__}",
                "tests": _tests_for(rule.rule_id),
            }
        )
    return result


def render_json(data: list[dict[str, Any]]) -> str:
    return json.dumps(data, indent=2) + "\n"


def render_markdown(data: list[dict[str, Any]]) -> str:
    lines = [
        "# ADR-002 Traceability Matrix",
        "",
        "Generated by `scripts/generate_traceability.py` (`make traceability`).",
        "One row per validation rule: **Rule → Validator → Test(s)**. Rule ids are a",
        "**frozen namespace** — never reused or renumbered.",
        "",
        "| Rule ID | Group | Severity | ADR Reference | Description | Validator | Test(s) |",  # noqa: E501
        "|---|---|---|---|---|---|---|",
    ]
    for row in data:
        tests = "<br>".join(row["tests"]) or "—"
        lines.append(
            f"| {row['rule_id']} | {row['group']} | {row['severity']} | "
            f"{row['adr_reference']} | {row['description']} | `{row['validator']}` | {tests} |"  # noqa: E501
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    data = rows()
    _MD.write_text(render_markdown(data), encoding="utf-8")
    _JSON.write_text(render_json(data), encoding="utf-8")
    print(f"wrote {_MD} and {_JSON}")


if __name__ == "__main__":
    main()
